const jobs = [
  {
    jobTitle: "Software Engineer",
    jobDescription:
      "Develop and maintain software applications. Collaborate with cross-functional teams to define, design, and ship new features.",
    jobType: "Full-time",
    workType: "Onsite",
    location: "Chennai, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: ["HTML", "CSS", "JavaScript", "Node.js"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "Frontend Developer",
    jobDescription:
      "Design and implement UI components using HTML, CSS, and JavaScript. Ensure the technical feasibility of UI/UX designs.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Coimbatore, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "Backend Developer",
    jobDescription:
      "Develop server-side logic and maintain databases. Optimize applications for maximum speed and scalability.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Madurai, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: ["Node.js", "Express.js", "MongoDB", "API Development"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "DevOps Engineer",
    jobDescription:
      "Manage deployment pipelines and ensure software reliability. Implement and manage CI/CD pipelines.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Tiruchirappalli, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: ["Docker", "Kubernetes", "CI/CD", "AWS"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "Data Analyst",
    jobDescription:
      "Analyze and interpret complex data sets. Develop and implement data collection systems and other strategies that optimize statistical efficiency and quality.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Salem, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,00,000 - ₹6,00,000 per annum",
    skills: ["Python", "SQL", "Data Visualization", "Pandas"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "Mobile App Developer",
    jobDescription:
      "Design and develop mobile applications for Android and iOS. Work closely with other app development and technical teams.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Erode, Tamil Nadu",
    industry: "Information Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,50,000 - ₹9,00,000 per annum",
    skills: ["Java", "Swift", "React Native", "Flutter"],
    company: "670e2eff32313cf9ace4102a",
  },
  {
    jobTitle: "Renewable Energy Engineer",
    jobDescription:
      "Design and implement renewable energy systems. Conduct site assessments and prepare feasibility studies.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: ["Solar Energy", "Wind Energy", "System Design", "AutoCAD"],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Energy Consultant",
    jobDescription:
      "Provide consultation on sustainable energy solutions. Develop energy management strategies and conduct energy audits.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Coimbatore, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: [
      "Energy Auditing",
      "Sustainability Planning",
      "Data Analysis",
      "Project Management",
    ],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Solar Panel Technician",
    jobDescription:
      "Install and maintain solar panel systems. Perform routine maintenance and troubleshooting.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Madurai, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: [
      "Solar Installation",
      "Electrical Systems",
      "Troubleshooting",
      "Safety Protocols",
    ],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Wind Turbine Specialist",
    jobDescription:
      "Oversee the installation and maintenance of wind turbines. Ensure compliance with safety regulations.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Tiruchirappalli, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: [
      "Wind Turbine Installation",
      "Mechanical Systems",
      "Safety Compliance",
      "Electrical Engineering",
    ],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Sustainability Project Manager",
    jobDescription:
      "Lead sustainability projects and coordinate efforts across teams. Develop project plans and manage budgets.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Salem, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: [
      "Project Management",
      "Sustainability Planning",
      "Team Leadership",
      "Risk Management",
    ],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Environmental Analyst",
    jobDescription:
      "Analyze environmental data to assess energy project impacts. Prepare reports and present findings.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Erode, Tamil Nadu",
    industry: "Renewable Energy",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,00,000 - ₹6,00,000 per annum",
    skills: ["Data Analysis", "Environmental Science", "GIS", "Reporting"],
    company: "670e2eff32313cf9ace4102b",
  },
  {
    jobTitle: "Registered Nurse",
    jobDescription:
      "Provide patient care and assist with medical procedures. Educate patients and their families on health conditions.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Healthcare",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: [
      "Patient Care",
      "Medical Procedures",
      "EMR Systems",
      "Communication",
    ],
    company: "670e2eff32313cf9ace4102c",
  },
  {
    jobTitle: "Medical Billing Specialist",
    jobDescription:
      "Handle patient billing and insurance claims. Ensure accuracy in billing and resolve any discrepancies.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Healthcare",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: [
      "Patient Care",
      "Medical Procedures",
      "EMR Systems",
      "Communication",
    ],
    company: "670e2eff32313cf9ace4102c",
  },
  {
    jobTitle: "Healthcare Administrator",
    jobDescription:
      "Manage healthcare facilities and ensure efficient operations. Oversee budgeting, staff coordination, and compliance with healthcare regulations.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Healthcare",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: [
      "Healthcare Management",
      "Budgeting",
      "Staff Coordination",
      "Compliance",
    ],
    company: "670e2eff32313cf9ace4102c",
  },
  {
    jobTitle: "Physical Therapist",
    jobDescription:
      "Assist patients in recovering physical strength through therapy. Develop personalized exercise programs and provide injury prevention education.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Coimbatore, Tamil Nadu",
    industry: "Healthcare",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: [
      "Physical Therapy",
      "Patient Rehabilitation",
      "Exercise Programs",
      "Injury Prevention",
    ],
    company: "670e2eff32313cf9ace4102c",
  },
  {
    jobTitle: "E-Learning Developer",
    jobDescription:
      "Design and develop interactive e-learning courses and modules. Ensure courses are engaging and meet educational standards.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Madurai, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: [
      "Instructional Design",
      "HTML5",
      "SCORM",
      "Learning Management Systems (LMS)",
    ],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "Content Creator",
    jobDescription:
      "Create educational content and resources for digital platforms. Develop multimedia content that enhances learning experiences.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Tiruchirappalli, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,00,000 - ₹6,00,000 per annum",
    skills: ["Content Writing", "Multimedia Design", "SEO", "Education"],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "Learning Management System Administrator",
    jobDescription:
      "Manage and maintain the Learning Management System. Provide technical support and ensure system integration.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Salem, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: [
      "LMS Administration",
      "Data Management",
      "Technical Support",
      "System Integration",
    ],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "Educational Consultant",
    jobDescription:
      "Provide guidance on integrating technology into educational environments. Develop instructional strategies and support tech integration.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Erode, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: [
      "Educational Technology",
      "Consulting",
      "Instructional Strategies",
      "Tech Integration",
    ],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "Software Developer - EdTech",
    jobDescription:
      "Develop software solutions for the education industry. Collaborate with cross-functional teams to deliver high-quality products.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,50,000 - ₹9,00,000 per annum",
    skills: ["Python", "JavaScript", "API Development", "Database Management"],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "UX/UI Designer",
    jobDescription:
      "Design user-friendly interfaces for educational software and applications. Conduct user research and create prototypes.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Coimbatore, Tamil Nadu",
    industry: "Education Technology",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹4,00,000 - ₹8,00,000 per annum",
    skills: ["UX/UI Design", "Prototyping", "Adobe XD", "User Research"],
    company: "670e2eff32313cf9ace4102d",
  },
  {
    jobTitle: "Financial Analyst",
    jobDescription:
      "Analyze financial data and provide insights for decision-making. Prepare financial reports and forecasts.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Madurai, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: ["Financial Modeling", "Excel", "Data Analysis", "Market Research"],
    company: "670e2eff32313cf9ace4102e",
  },
  {
    jobTitle: "Investment Banker",
    jobDescription:
      "Assist clients in raising capital and managing investments. Conduct financial analysis and valuation.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Tiruchirappalli, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹6,00,000 - ₹12,00,000 per annum",
    skills: [
      "Corporate Finance",
      "Capital Markets",
      "Financial Modeling",
      "Valuation",
    ],
    company: "670e2eff32313cf9ace4102e",
  },
  {
    jobTitle: "Risk Management Consultant",
    jobDescription:
      "Assess and mitigate financial risks for clients. Develop risk management strategies and ensure compliance.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Salem, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: ["Risk Assessment", "Compliance", "Data Analysis", "Insurance"],
    company: "670e2eff32313cf9ace4102e",
  },
  {
    jobTitle: "Accountant",
    jobDescription:
      "Manage financial statements and bookkeeping for clients. Prepare tax returns and ensure compliance with financial regulations.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Erode, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹3,50,000 - ₹7,00,000 per annum",
    skills: ["Accounting", "Taxation", "Financial Reporting", "Bookkeeping"],
    company: "670e2eff32313cf9ace4102e",
  },
  {
    jobTitle: "Financial Consultant",
    jobDescription:
      "Provide financial advice and strategies for business growth. Conduct market analysis and develop financial plans.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Chennai, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: [
      "Consulting",
      "Financial Planning",
      "Strategy Development",
      "Market Analysis",
    ],
    company: "670e2eff32313cf9ace4102e",
  },
  {
    jobTitle: "Compliance Officer",
    jobDescription:
      "Ensure regulatory compliance within financial operations. Conduct audits and implement policies.",
    jobType: "Full-time, Part-time, Remote",
    workType: "Onsite, WFH, Hybrid",
    location: "Coimbatore, Tamil Nadu",
    industry: "Finance",
    experienceLevel: "Fresher, 1-3 years",
    salaryRange: "₹5,00,000 - ₹10,00,000 per annum",
    skills: [
      "Consulting",
      "Financial Planning",
      "Strategy Development",
      "Market Analysis",
    ],
    company: "670e2eff32313cf9ace4102e",
  },
];

export default jobs;
