const skills = [
  "Educational Technology",
  "Consulting",
  "Instructional Strategies",
  "Tech Integration",
  "Corporate Finance",
  "Capital Markets",
  "Financial Modeling",
  "Valuation",
  "Financial Planning",
  "Strategy Development",
  "Market Analysis",
  "Risk Assessment",
  "Compliance",
  "Data Analysis",
  "Insurance",
  "Physical Therapy",
  "Patient Rehabilitation",
  "Exercise Programs",
  "Injury Prevention",
  "LMS Administration",
  "Data Management",
  "Technical Support",
  "System Integration",
  "Accounting",
  "Taxation",
  "Financial Reporting",
  "Bookkeeping",
  "Python",
  "JavaScript",
  "API Development",
  "Database Management",
  "UX/UI Design",
  "Prototyping",
  "Adobe XD",
  "User Research",
  "Instructional Design",
  "HTML5",
  "SCORM",
  "Learning Management Systems (LMS)",
  "Content Writing",
  "Multimedia Design",
  "SEO",
  "Education",
  "Excel",
  "Market Research",
  "Solar Installation",
  "Electrical Systems",
  "Troubleshooting",
  "Safety Protocols",
  "Solar Energy",
  "Wind Energy",
  "System Design",
  "AutoCAD",
  "Environmental Science",
  "GIS",
  "Reporting",
  "Healthcare Management",
  "Budgeting",
  "Staff Coordination",
  "Java",
  "Swift",
  "React Native",
  "Flutter",
  "Patient Care",
  "Medical Procedures",
  "EMR Systems",
  "Communication",
  "Energy Auditing",
  "Sustainability Planning",
  "Project Management",
  "Wind Turbine Installation",
  "Mechanical Systems",
  "Safety Compliance",
  "Electrical Engineering",
  "Team Leadership",
  "Risk Management",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "AWS",
  "SQL",
  "Data Visualization",
  "Pandas",
  "HTML",
  "CSS",
  "React",
  "Cloud Computing",
  "Machine Learning",
  "Artificial Intelligence",
  "Data Mining",
  "Big Data",
  "Blockchain",
  "Cybersecurity",
  "DevOps",
  "Server Administration",
  "Network Security",
  "Penetration Testing",
  "Digital Marketing",
  "Content Management",
  "Brand Strategy",
  "Social Media Management",
  "Advertising",
  "Public Relations",
  "Graphic Design",
  "Video Editing",
  "3D Modeling",
];

export default skills;
